import { Component, OnInit } from '@angular/core';
import { CarouselData } from './carouselData';
import { CarouselDataSm } from './carouselDataSm';
@Component({
  selector: 'app-carousel-multi-item-le',
  templateUrl: './carousel-multi-item-le.component.html',
  styleUrls: ['./carousel-multi-item-le.component.scss']
})
export class CarouselMultiItemLeComponent implements OnInit {
  carouselItem:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/1.jpg',
      h4Data:'ESTEVAN ORIOL',
      pData:'2021',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/2.jpg',
      h4Data:'CEKIOS',
      pData:'2020',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/3.jpg',
      h4Data:'SATONE',
      pData:'2020',
    },
  ]
  carouselItem1:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/4.jpg',
      h4Data:'FAKSO',
      pData:'2020',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/5.jpg',
      h4Data:'JULIONE',
      pData:'2020',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/6.jpg',
      h4Data:'MECRO',
      pData:'2020',
    },
  ]
  carouselItem2:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/7.jpg',
      h4Data:'ROSY ONE',
      pData:'2020',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/8.jpg',
      h4Data:'TREZE',
      pData:'2020',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/9.jpg',
      h4Data:'HENSE',
      pData:'2020',
    },
  ]
  carouselItem3:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/10.jpg',
      h4Data:'ACHES',
      pData:'2019',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/11.jpg',
      h4Data:'KATUN',
      pData:'2019',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/12.jpg',
      h4Data:'DABSMYLA',
      pData:'2019',
    },
  ]
  carouselItem4:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/13.jpg',
      h4Data:'LADY PINK',
      pData:'2019',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/14.jpg',
      h4Data:'PEZ',
      pData:'2019',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/15.jpg',
      h4Data:'JEAN BASQUIAT',
      pData:'2019',
    },
  ]
  carouselItem5:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/16.jpg',
      h4Data:'WILD STYLE',
      pData:'2018',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/17.jpg',
      h4Data:'MUSA 71',
      pData:'2018',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/18.jpg',
      h4Data:'HUEMAN',
      pData:'2018',
    },
  ]
  carouselItem6:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/19.jpg',
      h4Data:'ANDRÈ SARAVIA',
      pData:'2018',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/20.jpg',
      h4Data:'PESIMO',
      pData:'',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/21.jpg',
      h4Data:'ENTES',
      pData:'2018',
    },
  ]
  carouselItem7:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/22.jpg',
      h4Data:'EL MAC',
      pData:'2017',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/23.jpg',
      h4Data:"IT'S A LIVING",
      pData:'2017',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/24.jpg',
      h4Data:'ZEZAO',
      pData:'2017',
    },
  ]
  carouselItem8:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/25.jpg',
      h4Data:'SATURNO',
      pData:'2016',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/26.jpg',
      h4Data:'VOGUE',
      pData:'2016',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/27.jpg',
      h4Data:'CRYPTIK',
      pData:'2016',
    },
  ]
  carouselItem9:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/28.jpg',
      h4Data:'REMIO X ROSE BETON',
      pData:'CEET',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/29.jpg',
      h4Data:'CEET',
      pData:'2016',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/30.jpg',
      h4Data:'OKUDA',
      pData:'2015',
    },
  ]
  carouselItem10:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/31.jpg',
      h4Data:'JACE',
      pData:'2015',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/32.jpg',
      h4Data:'GREEMS',
      pData:'2015',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/33.jpg',
      h4Data:'DABS & MILA',
      pData:'2015',
    },
  ]
  carouselItem11:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/34.jpg',
      h4Data:'SINO',
      pData:'2015',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/35.jpg',
      h4Data:'OG SLICK',
      pData:'2015',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/36.jpg',
      h4Data:'INTI',
      pData:'2015',
    },
  ]
  carouselItem12:CarouselData[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/37.jpg',
      h4Data:'DALEK',
      pData:'2014',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/38.jpg',
      h4Data:'DR. REVOLT',
      pData:'2014',
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/39.jpg',
      h4Data:'Bue',
      pData:'2014',
    },
  ]
  carouselItemSm:CarouselDataSm[]=[
    {
      img:'../../../assets/img/carouselLimitedEdition/1.jpg',
      h4Data:'ESTEVAN ORIOL',
      pData:'2021',
      active:true,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/2.jpg',
      h4Data:'CEKIOS',
      pData:'2020',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/3.jpg',
      h4Data:'SATONE',
      pData:'2020',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/4.jpg',
      h4Data:'FAKSO',
      pData:'2020',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/5.jpg',
      h4Data:'JULIONE',
      pData:'2020',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/6.jpg',
      h4Data:'MECRO',
      pData:'2020',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/7.jpg',
      h4Data:'ROSY ONE',
      pData:'2020',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/8.jpg',
      h4Data:'TREZE',
      pData:'2020',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/9.jpg',
      h4Data:'HENSE',
      pData:'2020',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/10.jpg',
      h4Data:'ACHES',
      pData:'2019',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/11.jpg',
      h4Data:'KATUN',
      pData:'2019',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/12.jpg',
      h4Data:'DABSMYLA',
      pData:'2019',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/13.jpg',
      h4Data:'LADY PINK',
      pData:'2019',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/14.jpg',
      h4Data:'PEZ',
      pData:'2019',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/15.jpg',
      h4Data:'JEAN BASQUIAT',
      pData:'2019',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/16.jpg',
      h4Data:'WILD STYLE',
      pData:'2018',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/17.jpg',
      h4Data:'MUSA 71',
      pData:'2018',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/18.jpg',
      h4Data:'HUEMAN',
      pData:'2018',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/19.jpg',
      h4Data:'ANDRÈ SARAVIA',
      pData:'2018',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/20.jpg',
      h4Data:'PESIMO',
      pData:'',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/21.jpg',
      h4Data:'ENTES',
      pData:'2018',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/22.jpg',
      h4Data:'EL MAC',
      pData:'2017',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/23.jpg',
      h4Data:"IT'S A LIVING",
      pData:'2017',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/24.jpg',
      h4Data:'ZEZAO',
      pData:'2017',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/25.jpg',
      h4Data:'SATURNO',
      pData:'2016',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/26.jpg',
      h4Data:'VOGUE',
      pData:'2016',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/27.jpg',
      h4Data:'CRYPTIK',
      pData:'2016',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/28.jpg',
      h4Data:'REMIO X ROSE BETON',
      pData:'CEET',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/29.jpg',
      h4Data:'CEET',
      pData:'2016',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/30.jpg',
      h4Data:'OKUDA',
      pData:'2015',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/31.jpg',
      h4Data:'JACE',
      pData:'2015',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/32.jpg',
      h4Data:'GREEMS',
      pData:'2015',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/33.jpg',
      h4Data:'DABS & MILA',
      pData:'2015',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/34.jpg',
      h4Data:'SINO',
      pData:'2015',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/35.jpg',
      h4Data:'OG SLICK',
      pData:'2015',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/36.jpg',
      h4Data:'INTI',
      pData:'2015',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/37.jpg',
      h4Data:'DALEK',
      pData:'2014',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/38.jpg',
      h4Data:'DR. REVOLT',
      pData:'2014',
      active:false,
    },
    {
      img:'../../../assets/img/carouselLimitedEdition/39.jpg',
      h4Data:'Bue',
      pData:'2014',
      active:false,
    },
  ]
  constructor() { }

  ngOnInit(): void {
  }

}
